---
title: "AFLW Player Profile"
output: html_document
---

```{r, eval=F,echo=F, warning=F, message=F}

library(dplyr)
library(tidyr)
library(httr)
library(jsonlite)
library(reactable)

aflw_details <-
  purrr::map_dfr(
    c(2017:2022,2101,2023),
    ~ content(
      GET(
        paste0('https://api.afl.com.au/statspro/playersStats/seasons/CD_S',.x,'264'),
        config = httr::add_headers("x-media-mis-token" = fitzRoy::get_afl_cookie())
      ),as = 'text',encoding = 'UTF-8') %>%
      jsonlite::fromJSON(flatten = T) %>% .[['players']] %>% mutate(season = .x))

aflw_player_details <- aflw_details %>% 
  group_by(playerId = readr::parse_number(playerId)) %>% 
  summarise(
    playerName = last(paste(playerDetails.givenName,playerDetails.surname)),
    age = last(playerDetails.age),
    height = last(playerDetails.heightCm),
    lastSeason = last(season),
    careerGames = sum(totals.matchesPlayed,na.rm=T),
    careerGoals = sum(totals.goals,na.rm=T),
    .groups = 'drop'
  )

```

<script src="https://unpkg.com/react-table@7.7.0/dist/react-table.production.min.js"></script>

```{js, echo=F, warning=F, message=F}
const Parameters = new URLSearchParams(location.search);
ID = Parameters.get("ID");

if(!ID) {
ID = 1005269;
window.location.href = `aflw_player_profile.html?ID=${ID}`;
}

var xhttp = new XMLHttpRequest();

xhttp.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200) {
  // Typical action to be performed when the document is ready:
  json = JSON.parse(xhttp.responseText);

  if(json[ID]) {
    playerDetails = json[ID].Details;

    document.getElementById('player-name').innerHTML = playerDetails.playerName;
    document.getElementById('player-age').innerHTML = "<b>Age: </b>"+   playerDetails.currentAge;
    document.getElementById('player-picture').src = "https://s.afl.com.au/staticfile/AFL%20Tenant/AFL/Players/ChampIDImages/AFLW/" +    playerDetails.lastSeason +"264/" + String(ID) + ".png";
    document.getElementById('player-height').innerHTML = "<b>Height: </b>" + playerDetails.height + "cm";
    document.getElementById('career-goals').innerHTML = "<b>Career Goals: </b>" +playerDetails.careerGoals;
    document.getElementById('career-games').innerHTML = "<b>Career Games: </b>" +playerDetails.careerGames;
    
    let tableTemplate = JSON.parse( `{"x":{"tag":{"name":"Reactable","attribs":{"data":{},"columns":[{"id":"season","name":"Season","type":"character","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":60,"sticky":"left"},{"id":"team","name":"Team","type":"character","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":55},{"id":"age","name":"Age","type":"numeric","format":{"cell":{"digits":0},"aggregated":{"digits":0}},"minWidth":45},{"id":"games","name":"G","type":"numeric","format":{"cell":{"digits":0},"aggregated":{"digits":0}},"minWidth":45,"sticky":"left"},{"id":"fantasy","name":"AF","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":55},{"id":"time_on_ground","name":"TOG%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":55},{"id":"possessions","name":"TOT","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"contested","name":"CON","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"groundball","name":"GBG","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"adv_receives","name":"HOR","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"uncontested","name":"UNC","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"gathers","name":"GTH","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"intercept_poss","name":"IP","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"cba","name":"CBA","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"cba_pc","name":"CBA%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":55},{"id":"clearances","name":"TOT","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"centre_clr","name":"CTR","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"stoppage_clr","name":"STP","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"disposals","name":"TOT","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"eff_disp","name":"EFF","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"disp_efcy","name":"DE%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"handballs","name":"HB","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"handball_efcy","name":"HE%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"kicks","name":"K","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"kick_efcy","name":"KE%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"kick_hb_ratio","name":"K:H","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"clangers","name":"CLG","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"metres","name":"MG","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":55},{"id":"metres_per_disp","name":"M/D","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"kickins","name":"KI","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"kickin_playon_rate","name":"PO%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"rebounds","name":"R50","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"inside_50s","name":"I50","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"bounces","name":"RB","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"marks","name":"TOT","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"contested_marks","name":"CON","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"lead_marks","name":"LD","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"uncontested_marks","name":"UNC","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"intercept","name":"IM","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"marks_F50","name":"F50","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"shots","name":"SH","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"goals","name":"G","type":"numeric","format":{"cell":{"digits":0},"aggregated":{"digits":0}},"minWidth":45},{"id":"behinds","name":"B","type":"numeric","format":{"cell":{"digits":0},"aggregated":{"digits":0}},"minWidth":45},{"id":"score","name":"T","type":"numeric","format":{"cell":{"digits":0},"aggregated":{"digits":0}},"minWidth":45},{"id":"goal_assists","name":"GA","type":"numeric","format":{"cell":{"digits":0},"aggregated":{"digits":0}},"minWidth":45},{"id":"involvements","name":"SI","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"launches","name":"SL","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"tackles","name":"TOT","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"tackles_in50","name":"I50","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"pressure","name":"TOT","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"pressure_def","name":"DH","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"pressure_fwd","name":"FH","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"spoils","name":"SP","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"one_percenters","name":"one_percenters","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"ooo_def","name":"DEF","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"ooo_def_loss","name":"DL","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"ooo_def_loss_rate","name":"DL%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"ooo_off","name":"OFF","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"ooo_off_win","name":"OW","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"ooo_off_win_rate","name":"OW%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"frees_for","name":"FOR","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"frees_against","name":"AGN","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"free_diff","name":"+/-","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"ruck_contests","name":"RC","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"hitouts","name":"HO","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"hitout_win","name":"HO%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"hitouts_adv","name":"HTA","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":45},{"id":"adv_rate","name":"HTA%","type":"numeric","format":{"cell":{"digits":1},"aggregated":{"digits":1}},"minWidth":55}],"columnGroups":[{"align":"left","name":"","columns":["season","team","age","games","fantasy","time_on_ground"]},{"align":"left","name":"Possessions","columns":["possessions","contested","groundball","adv_receives","uncontested","gathers","intercept_poss"]},{"align":"left","name":"Clearances","columns":["cba","cba_pc","clearances","centre_clr","stoppage_clr"]},{"align":"left","name":"Disposals","columns":["disposals","eff_disp","disp_efcy","kicks","kick_efcy","handballs","handball_efcy","kick_hb_ratio","clangers"]},{"align":"left","name":"Movement","columns":["metres","metres_per_disp","kickins","rebounds","inside_50s","bounces","rebounds","inside_50s","bounces"]},{"align":"left","name":"Marks","columns":["marks","contested_marks","lead_marks","uncontested_marks","intercept","marks_F50"]},{"align":"left","name":"Scoring","columns":["shots","goals","behinds","score","goals","behinds","goal_assists","involvements","launches"]},{"align":"left","name":"Defence","columns":["tackles","tackles_in50","pressure","pressure_def","pressure_fwd","spoils"]},{"align":"left","name":"1-on-1 Contests","columns":["ooo_def","ooo_def_loss","ooo_def_loss_rate","ooo_off","ooo_off_win","ooo_off_win_rate"]},{"align":"left","name":"Frees","columns":["frees_for","frees_against","free_diff"]},{"align":"left","name":"Ruck","columns":["ruck_contests","hitouts","hitouts_adv","hitout_win","adv_rate"]}],"pagination":false,"striped":true,"showSortIcon":false,"style":{"fontSize":"12px"},"elementId":"season-table","dataKey":"51ec6f59f5ec8708c7896334df020911"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}`);

  
  tableTemplate.x.tag.attribs.data = json[ID].Seasons;
  
  let div = document.querySelector("#seasons-div");
  const script = document.createElement('script');
  script.setAttribute('data-for', 'season-table');
  script.setAttribute('type', 'application/json');
  script.innerText = JSON.stringify(tableTemplate);
  div.append(script);
  
  
  }
  }
};

xhttp.open("GET", "data/aflw/aflw_player_profiles.json", true);

xhttp.send();

```

```{r, echo=F, warning=F, message=F}
library(htmltools)
library(bslib)
library(reactable)
library(dplyr)
library(htmlwidgets)



div(id = "player-section",class = "container-player",
    img(id="player-picture",class="player-picture"),
    div(
      h2(class = "player-name",id="player-name"),
      div(class = "text-container",
          span(id="player-age",class = "player-details"),
          span(id="player-height",class = "player-details"),
          span(id="career-games",class = "player-details"),
          span(id="career-goals",class = "player-details")
      )
    )
)

div(id = "seasons-div")


# Render with onRender
# renderWidget({
#   myWidget <- myWidget(tableTemplate)
#   onRender(myWidget, myJSFunction)
# })
```

```{r, eval = F, echo = F}
reactable(
  data = jsonlite::fromJSON("data/aflw/aflw_player_profiles.json")$`1005269`$Seasons %>% bind_rows(),
  resizable = F,
  pagination = F,
  searchable = F,
  striped = T,
  showSortIcon = F,
  elementId = "season-table",
  style = list(
    fontSize = "12px"
  ),
  defaultColDef = colDef(
    minWidth = 45,
    format = colFormat(digits = 1)
  ),
  columns = list(
    season = colDef("Season",minWidth = 60,sticky = "left"),
    team = colDef("Team",minWidth = 55,sticky = NULL),
    age = colDef("Age",format = colFormat(digits = 0)),
    games = colDef("G",format = colFormat(digits = 0)),
    fantasy = colDef("AF",minWidth = 55),
    time_on_ground = colDef("TOG%",minWidth = 55),
    possessions = colDef("TOT"),
    contested = colDef("CON"),
    groundball = colDef("GBG"),
    adv_receives = colDef("HOR"),
    uncontested = colDef("UNC"),
    gathers = colDef("GTH"),
    intercept_poss = colDef("IP"),
    cba = colDef("CBA"),
    cba_pc = colDef("CBA%",minWidth = 55),
    clearances = colDef("TOT"),
    centre_clr = colDef("CTR"),
    stoppage_clr = colDef("STP"),
    disposals = colDef("TOT"),
    eff_disp = colDef("EFF"),
    disp_efcy = colDef("DE%"),
    handballs = colDef("HB"),
    handball_efcy = colDef("HE%"),
    kicks = colDef("K"),
    kick_efcy = colDef("KE%"),
    kick_hb_ratio = colDef("K:H"),
    clangers = colDef("CLG"),
    metres = colDef("MG",minWidth = 55),
    metres_per_disp = colDef("M/D"),
    kickins = colDef("KI"),
    kickin_playon_rate = colDef("PO%"),
    rebounds = colDef("R50"),
    inside_50s = colDef("I50"),
    bounces = colDef("RB"),
    marks = colDef("TOT"),
    contested_marks = colDef("CON"),
    lead_marks = colDef("LD"),
    uncontested_marks = colDef("UNC"),
    intercept = colDef("IM"),
    marks_F50 = colDef("F50"),
    shots = colDef("SH"),
    goals = colDef("G",format = colFormat(digits = 0)),
    behinds = colDef("B",format = colFormat(digits = 0)),
    score = colDef("T",format = colFormat(digits = 0)),
    goal_assists = colDef("GA", format = colFormat(digits = 0)),
    involvements = colDef("SI"),
    launches = colDef("SL"),
    tackles = colDef("TOT"),
    tackles_in50 = colDef("F50"),
    pressure = colDef("TOT"),
    pressure_def = colDef("DH"),
    pressure_fwd = colDef("FH"),
    spoils = colDef("SP"),
    ooo_def = colDef("DEF"),
    ooo_def_loss = colDef("DL"),
    ooo_def_loss_rate = colDef("DL%"),
    ooo_off = colDef("OFF"),
    ooo_off_win = colDef("OW"),
    ooo_off_win_rate = colDef("OW%"),
    frees_for = colDef("FOR"),
    frees_against = colDef("AGN"),
    free_diff = colDef("+/-"),
    ruck_contests = colDef("RC"),
    hitouts = colDef("HO"),
    hitouts_adv = colDef("HTA"),
    hitout_win = colDef("HO%"),
    adv_rate = colDef("HTA%",minWidth = 55)
  ),
  defaultColGroup = colGroup(align = "left",sticky = NULL),
  columnGroups = list(
    colGroup(name = "",columns = c("team","age","games","fantasy","time_on_ground")),
    colGroup(name = "Possessions", columns = c("possessions","contested","groundball","adv_receives","uncontested","gathers","intercept_poss")),
    colGroup(name = "Clearances",columns = c("cba","cba_pc","clearances","centre_clr","stoppage_clr")),
    colGroup(name = "Disposals", columns = c("disposals","eff_disp","disp_efcy","kicks","kick_efcy","handballs","handball_efcy","kick_hb_ratio","clangers")),
    colGroup(name = "Movement", columns = c("metres","metres_per_disp","kickins","rebounds","inside_50s","bounces","rebounds","inside_50s","bounces")),
    colGroup(name = "Marks", columns = c("marks","contested_marks","lead_marks","uncontested_marks","intercept","marks_F50")),
    colGroup(name = "Scoring", columns = c("shots","goals","behinds","score","goals","behinds","goal_assists","involvements","launches")),
    colGroup(name = "Tackles", columns = c("tackles","tackles_in50")),
    colGroup(name = "Pressure", columns = c("pressure","pressure_def","pressure_fwd")),
    colGroup(name = "1-on-1 Contests", columns = c("spoils","ooo_def","ooo_def_loss","ooo_def_loss_rate","ooo_off","ooo_off_win","ooo_off_win_rate")),
    colGroup(name = "Frees", columns = c("frees_for","frees_against","free_diff")),
    colGroup(name = "Ruck", columns = c("ruck_contests","hitouts","hitouts_adv","hitout_win","adv_rate"))
  )
)
)
```