---
title: "AFL Fantasy Captains Rankings 2023"
output: html_document
---

What was your captaincy average in 2023? Here are the top 10,000 teams and how they went at picking their double points.

### 2023 Summary

**Loophole Usage**: 35.86% | **Taken VC Average**: 130.93 | **Fallback C Average**: 111.92

**Top 100 Average**: 121.30 | **Top 1000 Average**: 119.96 | **Top 10,000 Average**: 118.73

* **Rank** - Captain average rank in the top 10,000
* **Average** - Season captain average
* **Loops** - Number of rounds activating the vice captain loophole
* **VC Average** - The vice captain average
* **Taken VC Average** - The average VC score the coach activated as captain
* **Fallback C Average** - The captain average when the VC is not activated
* **Errors** - Number of rounds where the VC outscored the captain
* **<100** - Number of rounds where the taken captain scored under 100 points

```{r, echo=F, message=F, warning=F}
library(reactable)
library(htmltools)
library(dplyr)

captains <- readRDS("C:/Users/jpopo/Documents/Rstats/Captains2024.rds") %>% 
  dplyr::mutate(Rank = rank(-Average,ties.method = "min")) %>% 
  dplyr::relocate(Rank, .before = Average)

reactable(
  captains[,-c(1,4)],
  defaultSorted = c("Average"),
  defaultSortOrder = "desc",
  showSortIcon = FALSE,
  showPageSizeOptions = TRUE,
  striped = TRUE,
  pageSizeOptions = c(50,100,200),
  elementId = "fantasy-captains-table",
  defaultPageSize = 50,
  searchable = T,
  columns = list(
    name = colDef(
      name = "Team",
      sticky = "left",
      defaultSortOrder = "asc",
      minWidth = 200
    ),
    overall_rank = colDef(
      name = "Overall Rank",
      defaultSortOrder = "asc"
    ),
    coach = colDef(
      name = "Coach"
    ),
    Average = colDef(
      format = colFormat(digits =1)
    ),
    `VC Average` = colDef(
      name = "VC Average",
      format = colFormat(digits = 1)
    ),
    `Taken VC Average` = colDef(
      name = "Taken VC Av",
      format = colFormat(digits =1)
    ),    
    `Fallback C Average` = colDef(
      name = "Fallback C Av",
      format = colFormat(digits =1)
    )
  )
)

```

